### ISSUE TITLE
A beginner's question

### ISSUE THREAD

**Issue by happy888liu** [mcgheecc/covid-compare#1]
hello,i am learning springbatch, i find this project, this project code and structure  is quite perfect,but i have a question,what's advantage of springbatch in this project :sob:

**Comment by mcgheecc** [comment]
Hi, 
Thanks. 
I guess the main advantage is in the init country data job that uses remote chunking. You can add as many slaves as you like to retrieve the country statistics concurrently, therefore improving performance significantly. Other advantages are the built in retry and skip functionality. 
The main reason I had for using spring batch though was just a quick refresher for myself as I'd not used it for a couple of years. 

If you need any help with spring batch feel free to email me at chris.mcghee@gmail.com.
